# general settings
name: RRDB_MWN_x4_ZOOM_scratch
model_type: MWNSRModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: ZOOM
    type: PairedMetaImageDataset
    dataroot_gt: datasets/ZOOM/train/HR_sub
    dataroot_lq: datasets/ZOOM/train/LR/4_sub
    dataroot_meta_gt: datasets/ZOOM/train/HR_4_meta
    dataroot_meta_lq: datasets/ZOOM/train/LR_4_meta
    io_backend:
      type: disk

    gt_size: 96
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: ZOOM
    type: PairedImageDataset
    dataroot_gt: datasets/ZOOM/test/HR_sub
    dataroot_lq: datasets/ZOOM/test/LR/4_sub
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: 1

network_mwn:
  type: SimpleMWNet

# path
path:
  pretrain_network_g: ~
  strict_load_g: False
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  weight_vis: False
  start_meta: 5000 # start meta learning (LRE) after 20000 iterations
  meta_loss: GW
  lre_batch_only: True

  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  optim_meta_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]


  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: !!float 5e3
  save_img: True

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

    ssim: # metric name, can be arbitrary
        type: calculate_ssim
        crop_border: 4
        test_y_channel: false

    niqe: # metric name, can be arbitrary
        type: calculate_niqe
        crop_border: 4
    lpips:
        type: calculate_lpips
        crop_border: 4

logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
