# general settings
name: SwinIR_x4_ZOOM_scratch
model_type: SwinIRModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: ZOOM
    type: PairedImageDataset
    dataroot_gt: datasets/ZOOM/train/HR_sub
    dataroot_lq: datasets/ZOOM/train/LR/4_sub
    io_backend:
      type: disk

    gt_size: 64
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ZOOM
    type: PairedImageDataset
    dataroot_gt: datasets/ZOOM/test/HR_sub
    dataroot_lq: datasets/ZOOM/test/LR/4_sub
    io_backend:
      type: disk

# network structures
network_g:
  type: SwinIR
  upscale: 1
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 255.
  depths: [6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  resi_connection: '1conv'


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000]
    gamma: 0.5

  total_iter: 150000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: !!float 5e3
  save_img: True

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

    ssim: # metric name, can be arbitrary
        type: calculate_ssim
        crop_border: 4
        test_y_channel: false


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
