# general settings
name: RCANx3_scratch_DIV2K_MWNet_misaligned
model_type: MWNSRModel
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedMetaImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub_misaligned
    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X3_sub
    dataroot_meta_gt: datasets/DIV2K/DIV2K_meta_HR_sub
    dataroot_meta_lq: datasets/DIV2K/DIV2K_meta_LR_bicubic/X3_sub
    io_backend:
      type: disk

    gt_size: 120
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 3
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 10
    prefetch_mode: ~
  val:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_valid_HR_sub
    dataroot_lq: datasets/DIV2K/DIV2K_valid_LR_bicubic/X3_sub
    io_backend:
      type: disk

# network structures
network_g:
  type: RCAN
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_group: 10
  num_block: 15
  squeeze_factor: 16
  upscale: 3
  res_scale: 1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]

network_mwn:
  type: SimpleMWNet
  input: 3
  hidden: 100
  output: 1

# path
path:
  pretrain_network_g: ~
  strict_load_g: False
  resume_state: ~
  pretrain_network_v: ~
  strict_load_v: False

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  optim_meta_g:
    type: SGD
    lr: !!float 1e-4
    momentum: 0.9
    nesterov: True
    weight_decay: !!float 1e-4

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

val:
  val_freq: !!float 5e3
  save_img: True

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

    ssim: # metric name, can be arbitrary
        type: calculate_ssim
        crop_border: 4
        test_y_channel: false


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

