# general settings
name: DAM_DIV2K_CTX_misaligned
model_type: TTSRModel
scale: 3
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: TripleImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub_misaligned
    dataroot_ref: datasets/DIV2K/DIV2K_train_HR_sub_misaligned
    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X3_sub
    io_backend:
      type: disk

    gt_size: 240
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: DIV2K
    type: TripleImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_valid_HR_sub
    dataroot_ref: datasets/DIV2K/DIV2K_valid_HR_sub
    dataroot_lq: datasets/DIV2K/DIV2K_valid_LR_bicubic/X3_sub
    io_backend:
      type: disk

# network structures
network_g:
  type: DAModule
  in_ch: 3
  feat_ch: 64
  out_ch: 3
  demodulate: true
  requires_grad: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: ContextualLoss
    band_width: !!float 0.5
    vgg_layer: conv4_4
    loss_type: cosine
    loss_weight: !!float 1.0
    reduction: mean

val:
  val_freq: !!float 1e4
  save_img: True

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

    ssim: # metric name, can be arbitrary
        type: calculate_ssim
        crop_border: 4
        test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
